# Watches for changes in file system and reloads browser automatically. 
# Run using bundle:
#     
#     bundle exec guard
# 
# You also need the Chrome Livereload add-on.
#

guard 'livereload' do
  watch(%r{views/.+\.erb$})
  watch(%r{views/layouts/.+\.erb$})
  watch(%r{stylesheets/.+\.(scss|css)$})
  watch(%r{public/javascripts/.+\.js})
end
